# Generated by Django 5.0.4 on 2024-05-04 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created_dates')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_date')),
                ('email', models.EmailField(blank=True, max_length=225, null=True, unique=True, verbose_name='Email')),
                ('name', models.CharField(blank=True, max_length=225, null=True, verbose_name='Name')),
                ('username', models.CharField(blank=True, max_length=225, null=True, unique=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=225, null=True, verbose_name='Password')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date_joined')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Last_login')),
                ('last_logout', models.DateTimeField(blank=True, null=True, verbose_name='Last_logout')),
                ('last_active', models.DateTimeField(blank=True, null=True, verbose_name='Last_active')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_logged_in', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is_active')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='GeneratedAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created_dates')),
                ('updated_date', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_date')),
                ('token', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
