# Generated by Django 5.0.4 on 2024-05-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_users_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_amdin',
            field=models.BooleanField(default=False),
        ),
    ]
